config/routes.rb
Hashpageme::Application.routes.draw do

  resources :hpage
  
  root :to => "hpage#index"
  
  match "/auth/twitter/callback" => "sessions#create"
  match "/twitter/signout" => "sessions#destroy", :as => :signout
	match "/auth/failiure" => "sessions#failure"
  
  get '/:id' => "hpage#show", as: :profile
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :header, :user_id
  
  belongs_to :user
  
  has_many :hashtags
  has_many :tweets
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  attr_accessible :category_id, :tag, :user_id
  
  belongs_to :user
  belongs_to :category
  
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :category_id, :text, :user_id
  
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :handle, :name, :photo, :provider, :uid
  
  has_many :categories
  has_many :hashtags
  has_many :tweets
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"] 
      user.photo = auth["info"]["image"]
      user.handle = auth["info"]["nickname"].downcase     
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def require_login
    if session[:user_id].blank?
      redirect_to root_url, notice: "You must be logged in to be here!"
    end
  end
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]    
  end
end

app/controllers/hpage_controller.rb
class HpageController < ApplicationController
  
  include HpageHelper
  
  before_filter :require_login, :only => [:new, :create]

  def new
    categories = current_user.categories
    if !categories.empty?
      if categories[0]
        @cat1 = categories[0].header
        @tags1 = gather_hashtags(categories[0])
      else
        @cat1 = nil
        @tags1 = []
      end
      if categories[1]
        @cat2 = categories[1].header
        @tags2 = gather_hashtags(categories[1])
      else
        @cat2 = nil
        @tags2 = []
      end
      if categories[2]
        @cat3 = categories[2].header
        @tags3 = gather_hashtags(categories[2])
      else
        @cat3 = nil
        @tags3 = []
      end    
    end
    @bio = current_user.bio
  end
  
  def create
    current_user.categories.each do |cat|
      cat.destroy
    end
    current_user.hashtags.each do |tag|
      tag.destroy
    end
    current_user.bio = params[:bio]
    current_user.save
    3.times { |i| create_category(params["category#{i+1}"], params["hash#{i+1}"]) }
    redirect_to profile_url("#{User.find_by_id(session[:user_id]).handle}")
  end 
  
  def index
  end

  def show
    @user = User.find_by_handle(params[:id].downcase)
    if @user.nil?
      flash[:no_page] = "Sorry--#{params[:id]} doesn't have a HashPage! Tell them to get one!"
      redirect_to root_url
    else
      update_local_tweets(@user)
      @categories = @user.categories
      @tweets = @user.tweets
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to new_hpage_url
  end
  
  def destroy
    session[:user_id] = nil
    flash[:signed_out] = "Signed out!"
    redirect_to root_url
  end

	def failure
		flash[:alert] = 'Something went wrong!'
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hpage_helper.rb
module HpageHelper
  
  def gather_hashtags(category)
    hashtags = Hashtag.find_all_by_category_id(category.id)
    tags = []
    hashtags.each do |hashtag|
      tags << hashtag.tag
    end
    return tags
  end
  
  def create_category(category_name, hash)
    if !category_name.empty? # change to nil?
      category = Category.new
      category.header = category_name
      category.user_id = session[:user_id]
      category.save
      if !hash.empty?
        if hash.include?(",")
          hash.split(", ").each do |tag|
            hashtag = Hashtag.new
            hashtag.tag = tag
            hashtag.category_id = Category.find_by_header_and_user_id(category_name, session[:user_id]).id
            hashtag.user_id = session[:user_id]
            hashtag.save 
          end
        else
          hashtag = Hashtag.new
          hashtag.tag = hash
          hashtag.category_id = category.id
          hashtag.user_id = session[:user_id]
          hashtag.save 
        end
      end
    end
  end
  
  def update_local_tweets(user)
    page = ((user.tweets.count)/100)+1
    all_tweets = Twitter::FetchesTweets.fetch(user.handle, page)
    all_tweets.each do |tweet|
      if user.tweets.find_by_text(tweet["text"].sub(/&amp;/, '&'))
      else
        t = Tweet.new
        t.text = tweet["text"].sub(/&amp;/, '&')
        t.user_id = user.id
        t.save
      end
    end
    hashes = user.hashtags
    local_tweets = user.tweets
    local_tweets.each do |tweet|
      hashes.each do |hash|
        if hash.tag
          if tweet.text.downcase.include?(hash.tag.downcase)
            tweet.category_id = hash.category_id
            tweet.save
          end
        end
      end
    end
  end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/hpage/index.html.erb
<%= flash[:signed_out] %>
<h1 id="headline1">Trend Yourself</h1>
  <h2 id="headline2">Show people what you're really into with a HashPage</h2>
    <div><%= link_to "See Example.", "http://www.hashpage.me/dmwoodall", class: "btn large btn-success" %></div>
     <section id="endorsements">
       <%= image_tag "example.png", class: "exampleImg" %>
      <div><quote>"If Twitter & LinkedIn had a baby, it would be a HashPage." <br>- Dave Hoover, Groupon</quote></div><br>
      <div><quote>Winner of "Most Likely to be a game changer" Award. <br>Code Academy, Spring 2012</quote></div>
     </section>
<section id="example">
  <h2>Organize your tweets by the hash tags you customize.</h2>
    <div><quote>HashPages combine real-time info with a consistent person.</quote></div>
</section>

<footer>
  <section id="side1">
  <h3>See Friends Trends</h3>
  <p>Tell your friends to trend themselves!</p>
  </section>
  <section id="side2">
    <h3>Have some say in what people see</h3>
    <p>Give people a clearer picture of your topics and interests. HashPage collects and organizes your tweets to show people what you're into.</p>
  </section>
</footer>

app/views/hpage/new.html.erb
<%= form_tag hpage_index_url, :method => "post" do %>
  Select three categories and hashtags separated by commas.
  <%= label_tag "Category 1:" %>
  <%= text_field_tag "category1", @cat1 %>
  <%= label_tag "Hash 1:" %>
  <%= text_field_tag "hash1", @tags1.join(", ") %>
  <br>
  <%= label_tag "Category 2:" %>
  <%= text_field_tag "category2", @cat2 %>
  <%= label_tag "Hash 2:" %>
  <%= text_field_tag "hash2", @tags2.join(", ") %>
  <br>
  <%= label_tag "Category 3:" %>
  <%= text_field_tag "category3", @cat3 %>
  <%= label_tag "Hash 3:" %>
  <%= text_field_tag "hash3", @tags3.join(", ") %>
  <br>
  <%= label_tag "About me:" %>
  <%= text_area_tag "bio", @bio %>
  <br>
  <%= submit_tag "Enter" %>
<% end %>

app/views/hpage/show.html.erb
<section id="hashpage">
<%= image_tag "walk.jpg", class: "headpic" %>
<section id="profileHead">
<%= image_tag @user.photo, class: "profilepic" %>
<h1 id="profileName"><%= @user.name %></h1>
<br>
<section id="aboutme">
<h2>About me:</h2>
<p> <%= @user.bio %> </p>
</section>
  <% i = 1 %>
  <% @categories.each do |category|%>  
    <section id="col<%= i %>">
      <h2><%= category.header %></h2>
      <ul>
        <% @tweets.find_all_by_category_id(category.id).each do |tweet| %>
          <li> <%= tweet.text %> </li>
        <% end %>
      </ul>
    </section>
    <% i += 1 %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hashpage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <link href='http://fonts.googleapis.com/css?family=Belgrano|Comfortaa:400,700,300|Imprima' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div class="container">
      <div class="content">
        <div class="row">

           <div class="span9">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>